[package]
org = "dumindusameendra"
name = "debug_transaction_test"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "l/myapp.jar"