[package]
org = "dumindusameendra"
name = "service"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

# [[platform.java11.dependency]]
# artifactId="sqlite-jdbc"
# version="3.36.0.1"
# groupId="org.xerial"

# [[platform.java11.dependency]]
# artifactId = "h2"
# version = "2.0.206"
# groupId = "com.h2database"
