[package]
org = "dumindusameendra"
name = "bug_endtransaction"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

# [[platform.java11.dependency]]
# artifactId="sqlite-jdbc"
# version="3.36.0.1"
# groupId="org.xerial"